"""Reproduce the adversarial-review statistics quoted in docs/PILOT-11-ownership.md.

Everything here is computed from the committed data shapes in out/ so the numbers in
the write-up can be regenerated by anyone with the JSONL files:

  1. Opus rival-frame ownership by "who produced the word" group (cell and fork level).
  2. Fork-level logistic regressions of Opus rival Yes on a produced-by-either flag,
     then adding log own-probability and log other-model probability (LR chi-square).
  3. Spearman of P(Yes) against log own-probability inside the produced set.
  4. Within-prompt permutation test for the other-model term: shuffle each cell's
     (p_own, p_other) pair among the cells of the same prompt, refit, and count how
     often the permuted other-model coefficient is at least as large as the observed.
  5. The local (Qwen) intent-question Spearman under the specifications that were
     quoted, so the doc can cite one of them unambiguously.

Zero probabilities are floored at half a count out of 48 forks (1/96) before taking
logs; the choice is stated in the doc.

Usage: .venv/bin/python selfportrait/ownership_review_stats.py [n_perm]
"""

from __future__ import annotations

import json
import math
import os
import sys
from collections import defaultdict
from pathlib import Path

import numpy as np
from scipy.stats import chi2, fisher_exact, spearmanr
from sklearn.linear_model import LogisticRegression

ROOT = Path(__file__).resolve().parents[1]
FLOOR = 1 / 96
PREFIX = os.environ.get("SP_OUT_PREFIX", "own")

def load_json_array(p):
    if not p.exists():
        return []
    with open(p) as f:
        return json.load(f)


def load_jsonl(p):
    if not p.exists():
        return []
    with open(p) as f:
        return [json.loads(line) for line in f]


# pooled Claude (haiku/opus) probability, used as the "other-model" fallback
# when a row/cell carries no other judge's p_* field at all (e.g. the gpt
# judge, which only ever records p_gpt).
_OWN_CELLS_FALLBACK = {
    (c["prompt"], c["answer"]): c
    for c in load_json_array(ROOT / "out" / "own_cells.json")
}


def lg(p: float) -> float:
    return math.log(max(p, FLOOR))


def other_prob(d, own_key):
    """Probability under 'the other model' for a row/cell dict d whose own
    probability lives at own_key (e.g. "p_opus")."""
    ks = sorted(k for k in d if k.startswith("p_") and k not in (own_key, "p_own"))
    if len(ks) == 1:
        return d.get(ks[0]) or 0.0
    if not ks:
        c = _OWN_CELLS_FALLBACK.get((d.get("prompt"), d.get("answer")))
        if c:
            return max(c.get("p_haiku", 0) or 0, c.get("p_opus", 0) or 0)
        return 0.0
    return max(d.get(k) or 0.0 for k in ks)


def load():
    cells = {
        (c["prompt"], c["answer"]): c
        for c in load_json_array(ROOT / "out" / f"{PREFIX}_cells.json")
    }
    rows = [r for r in load_jsonl(ROOT / "out" / f"{PREFIX}_judgements.jsonl") if r["yn"] in ("yes", "no")]
    return cells, rows


def loglik(X, y):
    """Log-likelihood of an unpenalised logistic fit; X may be empty (intercept only)."""
    if X.shape[1] == 0:
        p = y.mean()
        return float(np.sum(y * math.log(p) + (1 - y) * math.log(1 - p)))
    m = LogisticRegression(penalty=None, max_iter=5000).fit(X, y)
    pr = np.clip(m.predict_proba(X)[:, 1], 1e-12, 1 - 1e-12)
    return float(np.sum(y * np.log(pr) + (1 - y) * np.log(1 - pr)))


def lr_test(X0, X1, y):
    stat = 2 * (loglik(X1, y) - loglik(X0, y))
    df = X1.shape[1] - X0.shape[1]
    return stat, chi2.sf(stat, df)


def main():
    n_perm = int(sys.argv[1]) if len(sys.argv) > 1 else 5000
    cells, rows = load()
    # sorted descending reproduces the original hard-coded ("opus", "haiku")
    # order for the default two-judge run; order is otherwise immaterial.
    judges = sorted({r["judge"] for r in rows}, reverse=True)
    for judge in judges:
        own_key = f"p_{judge}"
        sub = [
            r for r in rows
            if r["judge"] == judge and r["question"] == "rival" and r["tag"] != "off_category"
        ]
        print(f"\n=== {judge} judge, rival question, in-category cells: {len(sub)} forks ===")
        # 1. groups
        groups = defaultdict(list)
        for r in sub:
            po, ph = r[own_key], other_prob(r, own_key)
            g = ("both" if po > 0 and ph > 0 else "own_only" if po > 0
                 else "other_only" if ph > 0 else "neither")
            groups[g].append(r["yn"] == "yes")
        for g in ("own_only", "other_only", "both", "neither"):
            v = groups[g]
            ncell = len({(r["prompt"], r["answer"]) for r in sub
                         if (("both" if r[own_key] > 0 and other_prob(r, own_key) > 0
                              else "own_only" if r[own_key] > 0
                              else "other_only" if other_prob(r, own_key) > 0 else "neither") == g)})
            print(f"  {g:11s} P(yes)={np.mean(v):.3f}  forks={len(v)}  cells={ncell}")
        a, b = groups["own_only"], groups["other_only"]
        _, p = fisher_exact([[sum(a), len(a) - sum(a)], [sum(b), len(b) - sum(b)]])
        print(f"  own_only vs other_only Fisher p={p:.3f}  ({sum(a)}/{len(a)} vs {sum(b)}/{len(b)})")

        # 2. fork-level logistic, LR tests
        y = np.array([r["yn"] == "yes" for r in sub], dtype=float)
        flag = np.array([[float(r[own_key] > 0 or other_prob(r, own_key) > 0)] for r in sub])
        lown = np.array([[lg(r[own_key])] for r in sub])
        loth = np.array([[lg(other_prob(r, own_key))] for r in sub])
        empty = np.zeros((len(sub), 0))
        s, p = lr_test(empty, flag, y)
        print(f"  produced-by-either flag vs null: chi2={s:.1f} p={p:.2g}")
        s, p = lr_test(flag, np.hstack([flag, lown]), y)
        print(f"  + log p_own given flag:          chi2={s:.1f} p={p:.2g}")
        s, p = lr_test(flag, np.hstack([flag, loth]), y)
        print(f"  + log p_other given flag:        chi2={s:.1f} p={p:.2g}")
        s, p = lr_test(lown, np.hstack([lown, loth]), y)
        print(f"  log p_other given log p_own (no flag): chi2={s:.1f} p={p:.2g}  [pseudo-replicated over forks]")

        # 3. inside the produced set (p_own > 0), cell level
        cell_yes = defaultdict(list)
        for r in sub:
            cell_yes[(r["prompt"], r["answer"])].append(r["yn"] == "yes")
        prod = [(np.mean(v), lg(cells[k][own_key])) for k, v in cell_yes.items()
                if cells[k][own_key] > 0]
        rho, p = spearmanr([a for a, _ in prod], [b for _, b in prod])
        print(f"  inside own produced set: {len(prod)} cells, Spearman P(yes) vs log p_own rho={rho:+.2f} p={p:.2g}")
        allc = [(np.mean(v), lg(cells[k][own_key])) for k, v in cell_yes.items()]
        rho, p = spearmanr([a for a, _ in allc], [b for _, b in allc])
        print(f"  all in-category cells: {len(allc)}, Spearman rho={rho:+.2f} p={p:.2g}")

        # 4. within-prompt permutation for the other-model coefficient
        rng = np.random.default_rng(0)
        by_prompt = defaultdict(list)
        for k in cell_yes:
            by_prompt[k[0]].append(k)

        def coef_other(mapping):
            X = np.array([[lg(mapping[(r["prompt"], r["answer"])][0]),
                           lg(mapping[(r["prompt"], r["answer"])][1])] for r in sub])
            m = LogisticRegression(penalty=None, max_iter=5000).fit(X, y)
            return m.coef_[0][1]

        obs_map = {k: (cells[k][own_key], other_prob(cells[k], own_key)) for k in cell_yes}
        obs = coef_other(obs_map)
        hits = 0
        for _ in range(n_perm):
            perm = {}
            for ks in by_prompt.values():
                vals = [obs_map[k] for k in ks]
                rng.shuffle(vals)
                perm.update(dict(zip(ks, vals)))
            if abs(coef_other(perm)) >= abs(obs):
                hits += 1
        print(f"  other-model coefficient={obs:+.3f}; within-prompt permutation p={(hits + 1) / (n_perm + 1):.3f} ({n_perm} perms)")

    # 5. local arm intent Spearman under the candidate specifications
    local_path = ROOT / "out" / f"{PREFIX}_local.jsonl"
    print("\n=== Qwen intent question, Spearman specifications ===")
    if not local_path.exists():
        print(f"  insufficient data: {local_path.name} not found")
        return
    loc = load_jsonl(local_path)
    specs = {
        "in-category (excl off_category), log p_tf": (
            [r for r in loc if r["tag"] != "off_category"], "p_tf"),
        "in-category (excl off_category), p_sample": (
            [r for r in loc if r["tag"] != "off_category"], "p_sample"),
        "excl valid_unsampled only, p_sample": (
            [r for r in loc if r["tag"] != "valid_unsampled"], "p_sample"),
        "all 45 cells, log p_tf": (loc, "p_tf"),
    }
    for name, (sub, key) in specs.items():
        x = [math.log(max(r[key], 1e-12)) for r in sub]
        rho, p = spearmanr(x, [r["pyes_intent"] for r in sub])
        print(f"  {name:45s} n={len(sub):2d} rho={rho:+.2f} p={p:.3g}")


if __name__ == "__main__":
    main()
